In [9]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/ADANIGREEN.csv')

In [8]:
open = df.loc[18: 18 +5, 'open'].values
open

array([29.5, 28.5, 28.6, 28.5, 28.5, 28.5])

In [7]:
sum(open)/len(open)

28.683333333333334

In [11]:
MAX_NUM_SHARES = 2147483647
MAX_SHARE_PRICE = 10000
current_step = 18
np.array([
            df.loc[current_step: current_step +
                        5, 'open'].values / MAX_SHARE_PRICE,
            df.loc[current_step: current_step +
                        5, 'high'].values / MAX_SHARE_PRICE,
            df.loc[current_step: current_step +
                        5, 'low'].values / MAX_SHARE_PRICE,
            df.loc[current_step: current_step +
                        5, 'close'].values / MAX_SHARE_PRICE,
            df.loc[current_step: current_step +
                        5, 'volume'].values / MAX_NUM_SHARES,
        ])

array([[2.95000000e-03, 2.85000000e-03, 2.86000000e-03, 2.85000000e-03,
        2.85000000e-03, 2.85000000e-03],
       [2.95000000e-03, 2.89500000e-03, 2.89000000e-03, 2.85500000e-03,
        2.85500000e-03, 2.86000000e-03],
       [2.85000000e-03, 2.85000000e-03, 2.85000000e-03, 2.85000000e-03,
        2.85000000e-03, 2.85000000e-03],
       [2.85000000e-03, 2.85500000e-03, 2.85000000e-03, 2.85000000e-03,
        2.85000000e-03, 2.85000000e-03],
       [2.03001779e-04, 3.97483818e-05, 4.61898744e-05, 3.48016620e-05,
        1.24243554e-04, 6.21145591e-06]])

In [13]:
MAX_NUM_SHARES = 2147483647
MAX_SHARE_PRICE = 10000
current_step = 18
np.array([
            df.loc[current_step: current_step +
                        5, 'open'].values,
            df.loc[current_step: current_step +
                        5, 'high'].values,
            df.loc[current_step: current_step +
                        5, 'low'].values,
            df.loc[current_step: current_step +
                        5, 'close'].values,
            df.loc[current_step: current_step +
                        5, 'volume'].values,
        ])

array([[2.95000e+01, 2.85000e+01, 2.86000e+01, 2.85000e+01, 2.85000e+01,
        2.85000e+01],
       [2.95000e+01, 2.89500e+01, 2.89000e+01, 2.85500e+01, 2.85500e+01,
        2.86000e+01],
       [2.85000e+01, 2.85000e+01, 2.85000e+01, 2.85000e+01, 2.85000e+01,
        2.85000e+01],
       [2.85000e+01, 2.85500e+01, 2.85000e+01, 2.85000e+01, 2.85000e+01,
        2.85000e+01],
       [4.35943e+05, 8.53590e+04, 9.91920e+04, 7.47360e+04, 2.66811e+05,
        1.33390e+04]])